dagupdate yml 수정

diff --git a/.github/workflows/dagUpdate.yml b/.github/workflows/dagUpdate.yml
--- a/.github/workflows/dagUpdate.yml
+++ b/.github/workflows/dagUpdate.yml
@@ -1,31 +1,41 @@
 name: Sync DAGs to EC2
-
 on:
   push:
-    branches:
-      - main
+    branches: [ "main", "develop" ]
     paths:
       - 'airflow/**'
-
 jobs:
   sync-dags:
     runs-on: ubuntu-latest
     steps:
     - name: Checkout code
-      uses: actions/checkout@v3
-
+      uses: actions/checkout@v4
     - name: Install SSH key
-      uses: webfactory/ssh-agent@v0.5.1
+      uses: webfactory/ssh-agent@v0.9.0
       with:
         ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
-
+    - name: Debug EC2 host
+      run: |
+        echo "EC2 Host value: ${{ secrets.EC2_HOST }}"
+        nslookup ${{ secrets.EC2_HOST }} || echo "nslookup failed"
+        ping -c 4 ${{ secrets.EC2_HOST }} || echo "ping failed"
+      shell: bash
     - name: Add EC2 host key to known hosts
       run: |
         mkdir -p ~/.ssh
-        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
+        ssh-keyscan -v -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts || echo "ssh-keyscan failed, but continuing..."
+        echo "Contents of ~/.ssh/known_hosts:"
+        cat ~/.ssh/known_hosts
       shell: bash
-
+    - name: Test SSH connection
+      run: |
+        ssh -v -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'echo SSH connection successful' || echo "SSH connection failed"
+      shell: bash
+    - name: Create backup directory on EC2
+      run: |
+        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} 'mkdir -p /home/ubuntu/hori_project/Temp_Trend/airflow/dag_backups'
+      shell: bash
     - name: Sync DAGs to EC2
       run: |
-        rsync -avz --progress --delete --exclude='.*' ./airflow/dag/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/hori_project/Temp_Trend/airflow/dags/
+        rsync -avz --progress --update --backup --backup-dir=/home/ubuntu/hori_project/Temp_Trend/airflow/dag_backups ./airflow/dag/ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/hori_project/Temp_Trend/airflow/dags/
       shell: bash
